[package]
name = "playing-rustball"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-rt = "2.8.0"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
